### ISSUE TITLE
Wrong file links in problems pane

### ISSUE THREAD

**Issue by jlecour** [ansible-community/vscode-ansible#101]
**Describe the bug**
After installing this extension, I get "problems" reported about YAML files, but they reference files with a weirdly relative link that make them not clickable.

**To Reproduce**
1. Install the extension
2. open an editor with YAML files that include syntax errors
3. look at the "problems" pane
4. file links are relative (with bad reference) and not absolute

For example, I get links like `home/jlecour/ansible/playbook.yml` instead of `/home/jlecour/ansible/playbook.yml`.

**Expected behavior**
File links should be clickable.

```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 4.19.0-16-amd64
```

**Comment by ssbarnea** [comment]
Please find a way to reproduce the problem and describe it.

**Comment by jlecour** [comment]
Hi,

I'm on Debian with ansible-lint packaged :

```
$ ansible-lint --version
ansible-lint 4.1.0+dfsg.1
```

I'm in an environment where I can't use pypi, but only Debian Packages.

There is (apparently) no issue with ansible-lint itself. The paths from ansible-lint report are correct.

There is no custom ansible-lint configuration that I'm aware of.

**Comment by jlecour** [comment]
I've tried on macOS Big Sur with VSCode 1.56.1, ansible-lint 4.3, Python 3.9.1 and the same Ansible project.
Everything is displayed correctly.

There is probably something special on my Debian workstation. I'll let you know if I find the issue or if I have more information for you.

Thank you for your time and effort :+1:

**Comment by jlecour** [comment]
I've created a blank Ansible project, with no reference to external roles…
I get the same file link error.

On my Debian setup, I've tried to disable all extensions but the ones that are also installed on my Mac (Ansible Language 0.4.2, Jupyter 2021.3.832593372, Pylance 2021.5.1, Python 2021.5.82.9140558, YAML 0.18.0). Same file link error.

**Comment by ssbarnea** [comment]
I do know for sure that at some point I changed something around the formatting output of ansible-lint. I will close this bug becuase ansible-lint 4.1 is not supported, the only version supported is the latest.

**Comment by jlecour** [comment]
I understand the decision, but I still think that dropping support for the only version available in the current stable version of Debian is a bit harsh.

I'll try to find other ways to install a more recent version of ansible-lint but leaving the comfort (and peace of mind) of using only Debian packages is frustrating.

Thanks again for you work on these tools :+1:

**Comment by ssbarnea** [comment]
Please contact deb packagers and tell them that I am happy to help. I want to see them engaging with upstream projects on packaging. Sadly out of more than a 20 notable python projects I maintain I had only one case in the last years where packagers contacted the us and that was a dependency bug.

As now everyone has CI/CD pipelines it does make sense to automate packaging directly upstream. I am more than happy to welcome new github workflows that do that.
