### ISSUE TITLE
Missing .yaml extension in file matches

### ISSUE THREAD

**Issue by jorneilander** [ansible-community/vscode-ansible#102]
An example:

https://github.com/ansible-community/vscode-ansible/blob/5a2954607e1dc21b2de48d2633c13424c3acf0d0/package.json#L153-L159

Currently, it seems to be selectively set to include `.yaml` files into file matches throughout the file as opposed to only including `.yml` files. Considering `.yaml` is the [actual official YAML file extension](https://yaml.org/faq.html) it might be an idea to include both extensions in every file match.

**Comment by ssbarnea** [comment]
Sorry but posting a link to https://www.reddit.com/r/ansible/comments/cnsspu/yml_vs_yaml_file_extention/ewemsa5?utm_source=share&utm_medium=web2x&context=3 was needed ;)

AFAIK, Ansible uses only YML but if you can find in the wild examples of using YAML extension, feel free to propose a PR to fix it, I will not fight it. The reason why I excluded is that I wanted to avoid accidental use of Ansible schema on other YAML files unrelated to it.

**Comment by jorneilander** [comment]
I hereby consider Ansible to be psychopath and a serial killer ;)

https://github.com/ansible/ansible/blob/f99d0248517c9dacc4594bc87d54626cdce59bfd/lib/ansible/parsing/dataloader.py#L197-L223

At least Ansible itself checks for both. Should I find the time I'll see if I can create a PR.
