### ISSUE TITLE
fileMatch paths do not follow official Ansible code layout guidelines

### ISSUE THREAD

**Issue by blinkiz** [ansible-community/vscode-ansible#111]
In [README.md](https://github.com/ansible-community/vscode-ansible/blob/master/README.md#L25) it says filepaths should follow the [official Ansible code layout guidelines](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#collection-structure). Clicking on the link and this structure comes up:
```
collection/
├── docs/
├── galaxy.yml
├── meta/
│   └── runtime.yml
├── plugins/
│   ├── modules/
│   │   └── module1.py
│   ├── inventory/
│   └── .../
├── README.md
├── roles/
│   ├── role1/
│   ├── role2/
│   └── .../
├── playbooks/
│   ├── files/
│   ├── vars/
│   ├── templates/
│   └── tasks/
└── tests/
```
But this does not work because [package.json](https://github.com/ansible-community/vscode-ansible/blob/master/package.json#L136) defines other paths.

Solution is to change package.json or suggest another file structure that matches paths defined in package.json

**Comment by ssbarnea** [comment]
I am not sure which paths you find as not conforming as the page you mentioned was the main source for building these patterns.

**Comment by blinkiz** [comment]
Okay.
Then am doing something wrong.
have a file like collection/playbooks/tasks/sometasks.yml and it will complain about stuff like `Missing property "hosts"` which do only exists in my playbooks, not it dedicated tasks yml files.

running `ansible-lint collection/playbooks/main.yml` works fine without any errors.

**Comment by ssbarnea** [comment]
@blinkiz I suspect you are encountering a bug in vscode where `*` does go across file paths separators when it should. Also the order on which the patterns are looked up on is not really controllable.

Microsoft fixed the issue one week or two ago inside the json-language-server by adopting a newer glob library but our yaml-language-server did not get a new release yet. If you fail to convince it to pick the right schemas the only option is to wait for the upstream dependencies to be updated as there is nothing inside our extension that can be changed to make it work.

For me it appears to be working fine now but I am aware that there are cases where the patterns do overlap and you endup with an undesired schema being used.

Keep in mind that you can always define your own patterns inside settings.json, which take precedence over the ones exposed in extension settings. Reading https://github.com/redhat-developer/vscode-yaml#associating-schemas should help you.

**Comment by blinkiz** [comment]
You are spot on.
Adding this to my settings and it starts to work.
```json
"yaml.schemas": {
        "https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json": ["playbooks/tasks/*.yml"]
      },
```

But this does not work because my `playbooks/tasks/` files gets the playbook schema.
```json
    "yaml.schemas": {
        "https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json": ["playbooks/tasks/*.yml"],
        "https://github.com/ansible-community/schemas/raw/main/f/ansible-playbook.json": ["playbooks/*.yml"]
      },
```

Thanks for creating this nice feature for VSCode (VSCodium in my case). 🙂

**Comment by ssbarnea** [comment]
You are welcomed. If you have a minute or two please also do a review on https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible&ssr=false#review-details and start/watch the project.
