### ISSUE TITLE
ansible.cfg is not used if it is not the root of the project

### ISSUE THREAD

**Issue by karmicdude** [ansible-community/vscode-ansible#115]
**Describe the bug**

For example, there is a tree like this:
```
infra
├── README.md
├── ansible
│   ├── ansible.cfg
│   ├── group_vars
│   ├── .vault
│   ├── inventory.ini
│   └── playbooks
└── infra.code-workspace
```

```
# ansible.cfg
[defaults]
inventory=inventory.ini
vault_identity_list=all@.vault
```

If the ansible directory is in a subdirectory of project, vscode-ansible simply doesn't see it. As a result, the `extension.ansible.vault` command doesn't work, because it can't find the `vault_identity_list` setting.
If you run vscode from the subdirectory ansible, it works fine.

Maybe a feature should be added to specify the path to `ansible.cfg` and the `extension.ansible.vault` function will work relative to that path, or something like that. It's not really convenient to have to run an instance of vscode separately in the ansible directory in a large project to make encryption/decryption work on the fly.

**Comment by ssbarnea** [comment]
This is not really a bug, it is default ansible behavior. I see not reason why this extension should do anything in particular to address this unexpected use-case.  All the commands are executed inside the workspace root, so you can guess why it is not finding ansiblec.cfg.

I will close the ticket as I do not expect to see anyone fixing it. Still, if you make PR that adds a feature that enables your workflow without breaking it for others I will be happy to review and accept it.

**Comment by bendem** [comment]
I can appreciate that it's not the most commonly used setup, but I've actually come over this a few times already. Devops repository are great candidates for monorepos with a subfolder for ansible.

Python for example has a setting for lints and tests:
![py lint config for cwd](https://user-images.githubusercontent.com/2681677/196187325-cb06c6a6-de3c-448f-8cf4-519cf61cb8e8.png)
![py test config for cwd](https://user-images.githubusercontent.com/2681677/196187303-cdaaf7c9-1831-4b16-b407-ac01dfc5cf9c.png)

**Comment by tigattack** [comment]
@karmicdude please do, this sounds very useful :)

**Comment by karmicdude** [comment]
This approach is to use [direnv](https://direnv.net/) and [direnv vscode extension](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv). 
After installing it, create a `.envrc` file in the root of the project and set the global variable `ANSIBLE_CONFIG` as path of your `ansible.cfg`.
```bash
#!/usr/bin/env bash

export ANSIBLE_CONFIG=${PWD}/ansible/ansible.cfg
```

If done correctly, the extension will detect the new direnv config and offer to activate it. 
If you have a path to your vault file in your `ansible.cfg`, the encrypt, decrypt commands should work. 

```ini
; ansible.cfg
[defaults]
vault_password_file=.vault
...
```
That way it works well if you have a directory structure, for example:

```
monorepo/
├── .envrc
├── ansible/
│   ├── ansible.cfg
│   ├── group_vars/
│   ├── inventory.ini
│   ├── playbooks/
│   └── requirements.yaml
├── k8s/
├── packer/
└── terraform/
```

Unfortunately, this workaround is only suitable for simple workspaces with one monorepo. If you have multiple monorepos, with separate ansible projects that use vault with different settings and passwords, this will not work, because the global `.envrc` doesn't fit, and local ones (each repo has its own `.envrc`) will not change the `ANSIBLE_CONFIG` variable for the whole vscode, only for the terminal.

**Comment by tigattack** [comment]
Thanks @karmicdude, this is really helpful 🙏

**Comment by karmicdude** [comment]
Why not? I think the vscode-ansble extension just calls ansible-vault under the hood, which explicitly reports that it can't find any vault configuration (`no valid ansible vault config found, cannot de/-encrypt`) and the environment variable solves it, pointing to ansible.cfg as the source of the vault configuration. This is default ansible behavior and https://github.com/ansible/vscode-ansible/blob/main/src/features/utils/ansibleCfg.ts#L33

**Comment by shinebayar-g** [comment]
This is such needed feature. My ansible playbooks live under `root/ansible` directory.

**Comment by ssbarnea** [comment]
If the `ansible.cfg` is not in the root of the project, we need to call both ansible-lint and ansible from a different CWD to get the desired behaviors. As of now, all operations are executed from project root, so I am not surprised that the deep `ansible.cfg` is not loaded.

**Comment by IceWreck** [comment]
I gave up and moved everything else to `other/` and ansible stuff to root in my Infrastructure repo.

Really tho, we need this.
