### ISSUE TITLE
The top element in the inventory is highlighted with an error

### ISSUE THREAD

**Issue by rosaLux161** [ansible-community/vscode-ansible#126]
**Describe the bug**

The top element in the inventory is highlighted with an error

**To Reproduce**

1. Create an inventory.yml in root directory
2. Fill inventory and open it
3. See this error at the top element:

```
A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead
```

**Expected behavior**
Inventories should not be treat as playbooks.

**Platform:**

VS Code: 1.56.2
Ansible Language Extension: v0.4.5
OS: macOS Big Sur 11.4
Ansible: 2.11.0

**Comment by ssbarnea** [comment]
Please provide more information, particularly the full path towards your `inventory.yml` file, as this may determine a change in behavior (picking wrong schema). The fact that it is at the root of your workspace does not affect that logic much as the patterns used are run on full paths. https://github.com/ansible-community/vscode-ansible/blob/master/package.json#L136-L203

**Comment by rosaLux161** [comment]
The project structure is as follows:

```
playbooks/
  playbook_1.yml
  ...
...
inventory.yml
...
```

The project directory is:
```
/Users/username/folder/folder/...
```

The playbook files seem to be interpreted correctly: https://github.com/ansible-community/vscode-ansible/blob/master/package.json#L137-L143
