### ISSUE TITLE
Add support for editing vaults

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/vscode-ansible#28]
As the title probably needs not more explanation, I should mention that there are already 4 extensions on vscode marketplace related to vault editing. Looking at them I noticed a pattern where almost each of them seems to be a fork of a previous one. I suspect what caused it is that original creator lost interest in maintaining it.

Instead of cluttering the marketplace with yet another extension that aims to address the same issue, I am inclined to see if one of the authors of these extensions is willing to join efforts and transition this feature into our extension, so we can have less extensions but better maintained.

Identified extensions:

* https://marketplace.visualstudio.com/items?itemName=flaunay.ansible-vault&ssr=false#overview by @FlorianLaunay with last release on 2020.12.19
* https://marketplace.visualstudio.com/items?itemName=wolfmah.ansible-vault-inline by @wolfmah with last release on 2020.07.13
* https://marketplace.visualstudio.com/items?itemName=spinosae.ansible-vault by @spinosae with last release on 2020.06.03
* https://marketplace.visualstudio.com/items?itemName=dhoeric.ansible-vault by @dhoeric with last release on 2018.04.30

# Vaulting use-cases
There are lots of way of working with secrets in Ansible and we will not be able to cover all from start, still we should document each one we identify and mention if they are supported or not, also allowing us to create tests for them later.

- [ ] single vault defined inside ansible.cfg: `vault_identity_list = .pass` or alternatives that can use names like foo@.pass or `default@.pass`. Ansible encrypts and decrypts files without any prompts in this case, it does not expect passsing a vault id.
- [ ] multiple vaults defined inside ansible.cfg: `vault_identity_list = foo@.pass bar@.pass2`. Ansible will try to guess decryption key to use if the encrypted text does not mention the name. Still encrypting requires mentioning the vault id.
- [ ] no vault_identity_list defined but `ansible_password_file` is defined, which points to the file with the secret.
- [ ] vault files that are executable ... (TBD)

**Comment by wolfmah** [comment]
I'm all in for merging my plugin into the official Ansible one.

As for helping, I'm not sure I'm the best here. I didn't re-invented the wheel here, I simply took dhoeric code (which in turn was inspired by an Atom plugin) to add an inline decoding/encoding capability.

Also, I don't use Ansible anymore for managing secrets so I have less motivation to keep it up to date. 😅 

I would gladly help in anyway I can and, once the vault feature is in mainline, to archive my repo and redirect people here.

**Comment by FlorianLaunay** [comment]
I'm all in too ! As @wolfmah has done with dhoeric's code, I just took his own and added some feature. I'm not a JS expert but I'm motivated to integrate my plugin as a new feature of this one.

**Comment by ssbarnea** [comment]
@wolfmah @FlorianLaunay Thank for replying so quickly, I did sent you an invite. I will look at both repos and see which ones should be the best candidate, my guess is that the newest one.

**Comment by FlorianLaunay** [comment]
Hi @ssbarnea

Thank you for the invite. I will work on this feature as soon as I can and will ping you when PR will be ready :wink:

**Comment by ssbarnea** [comment]
@FlorianLaunay Did you had any chance to look at it?

**Comment by FlorianLaunay** [comment]
> @FlorianLaunay Did you had any chance to look at it?

@ssbarnea It's in my todo list. I will start to work on this next week.

**Comment by FlorianLaunay** [comment]
Hi @ssbarnea . I have an almost functional feature. I will push it today or monday.

**Comment by ssbarnea** [comment]
I am really happy to hear that.

**Comment by FlorianLaunay** [comment]
Branch is pushed and PR #78 is opened as draft. I will let you take a look. I have proposed a new release : `0.4.0`

**Comment by FlorianLaunay** [comment]
@ssbarnea @JPinkney PR is ready for review :wink:
