### ISSUE TITLE
Find others to join the efforts

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/vscode-ansible#3]
I am looking for others to join my effort of building a vscode extension for Ansible content creators. The project is in planning phase and installing the extension does not enable any features yet.

I would not have started yet-another-extension endeavor unless I would have found one to contribute to. It would worth mentioning existing related extensions:

* [vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension provides schema verifications for YAML in a generic way. We are going to rely on it in order to enable Ansible schema, this extension can be seen as a dependency.
* [ansible (ms)](https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible) is an old Ansible extension developer by Microsoft China team which is currently [unmaintained](https://github.com/VSChina/vscode-ansible/issues/272) and which is not compatible with other YAML extensions, making it pretty much useful in practice.

As my JavaScript/TypeScript skills are not listed on my resume, I would likely progress very slow on this task and I will likely need help, especially for building the initial version. I am sure maintaining it will be much easier after we get the basics done.

If you want to help or know someone that could, please post a message. Thanks!

**Comment by pbpblush** [comment]
Message me, I can help once a month
