### ISSUE TITLE
[Question] Alternative to microsoft's ansible extension

### ISSUE THREAD

**Issue by lonix1** [ansible-community/vscode-ansible#44]
I used to use https://github.com/github.com/VSChina/vscode-ansible but that was deprecated.

I don't understand which is the recommended alternative - https://github.com/ansible-community/vscode-ansible (this one) or https://github.com/redhat-developer/vscode-yaml ?

And how do they differ?

**Comment by joshuawilson** [comment]
It looks like you are asking what is the difference between `yaml` and `ansible`. 

As I understand it, the ansible ext is using the yaml ext.

**Comment by JPinkney** [comment]
Yeah, so the way it works is that vscode-ansible (this extension) will automatically inject schemas into vscode-yaml so that you will have intellisense for ansible files automatically set up for you

**Comment by ssbarnea** [comment]
This extensions lists YAML one as a dependency, so I doubt you can even install it without also installing YAML one. 

Still, I would like to update the description text to make it clear that this extension "complements YAML extension by adding schema assignations and reporting problems from ansible-lint and yamllint."
