### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by skyfaller** [ansible-community/vscode-ansible#49]
Hi folks, is this open source? Could you please clarify what license this is released under? https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ssbarnea** [comment]
@skyfaller Sorry that it took so long, my initial guess that mentioning MIT on the package.json would be enough was likely not.

As you can see the repository has one of the most liberal possible licenses, so anyone could fork it to... become rich. My only hope it that it would persuade some to join-in and help it grow better.
