### ISSUE TITLE
Getting warning about name required even though task is named.

### ISSUE THREAD

**Issue by sabman3** [ansible-community/vscode-ansible#74]
I have several tasks showing as needing to be named even thought they are named. If there is a way t surpress this warning, that would be great.

VS Code: 1.55.2
OS: Fedora 33
Ansible Language: v0.3.1

**Comment by JPinkney** [comment]
Is it possible to post a small example?

**Comment by ssbarnea** [comment]
Closing as 0.3.2 was released and included https://github.com/ansible-community/vscode-ansible/pull/70 which is likely what could have caused this. From now on, please use discussions and let us file bugs once we identify a way to reproduce them.
