### ISSUE TITLE
Document support for inline encryting/decrypting

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/vscode-ansible#85]
As we now have vaulting support for full lines, it would be very useful to allow decryption and encryption of inline strings too.

There is an already existing extension that does this at [Vaulty (marketplace)](https://marketplace.visualstudio.com/items?itemName=codeflows.vaulty) - [Vaulty (github)](https://github.com/codeflows/vaulty) but I did not test it myself yet.

Still, I am sure it would be a good source of inspiration, maybe its author @codeflows would be interested into joining us?

**Comment by codeflows** [comment]
Hi! My extension should still work - it's pretty simple in that it only supports decryption. At the time I wrote the extension, the existing plugins I found replaced the encrypted file with the decrypted content, while my extension decrypts to a temporary buffer for viewing purposes only.

I haven't used Ansible in a couple of years and my time is limited at the moment, so unfortunately I can't be of more help ATM :)

**Comment by ssbarnea** [comment]
@codeflows Thanks for the quick reply! If at some point your extension becomes not usable or obsoleted by a newer one you could use the "unpublish" option from the marketplace to hide it. Also archiving the github repo after altering descriptio/url to point to a newer alternative/replacement is an option that can make easier for users search quests.

The reason I mention this is because I am trying to improve the situation of "ansible" extensions on vscode marketplace by reducing the number of outdated options. IMHO, "less is more" as the average user should spend less time guessing which option he should pick.  I already convinced another author to drop his extension and I am also happy that @FlorianLaunay helped migrating the vaulting code from his extension to this one. Having multiple users working together on a single extension is much better bet than relying on a single person, at least in the long run.

We will add that inline decryption/encryption feature for sure, in fact I find it even more useful than the full vaulted file one, which prevents searching for the place where a var is defined.

**Comment by FlorianLaunay** [comment]
Hi @ssbarnea the feature brought with #78 already manage inline encryption by selecting text before using keyboard shortcut to calle thé `ansible-vault` command

**Comment by ssbarnea** [comment]
In that case this feature should be added to the readme, https://github.com/ansible-community/vscode-ansible/blob/master/README.md -- Please do also include an animated gif when you do that, and mention that it fixes this bug.

**Comment by FlorianLaunay** [comment]
> In that case this feature should be added to the readme, https://github.com/ansible-community/vscode-ansible/blob/master/README.md -- Please do also include an animated gif when you do that, and mention that it fixes this bug.

@ssbarnea okay looking on that

**Comment by FlorianLaunay** [comment]
@ssbarnea , I pushed #109 to have a better documentation on this feature
